### ISSUE TITLE
Transaction build error. {"ownerId":"Field is required"}

### ISSUE THREAD

**Issue by eminogrande** [aeternity/aepp-playground#136]
When i try to deploy a contract via https://testing.playground.aepps.com i receive following error:

~ Transaction build error. {"ownerId":"Field is required"} 

![image](https://user-images.githubusercontent.com/3612477/60197833-8e0c2400-9840-11e9-82dc-f593566aedcd.png)

**Comment by maptuhec** [comment]
@emin Should be fixed now. Can you try and close the issue if you can't reproduce.

Thanks,
Martin
