### ISSUE TITLE
As a developer I want to be able to refresh the page or copy the link

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-playground#57]
Currently if a user tries to do this, the page shows "404"

child of #52

**Comment by sadiqevani** [comment]
This has to do with: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

This will be fixed when we figure out a deployment flow.

**Comment by sadiqevani** [comment]
@maptuhec when, where and how are we going to deal with deployment?
