### ISSUE TITLE
Research flexible solutions for the tour

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-playground#93]
We can research for flexible solutions for the tour of aeternity. We can schedule a meeting and discuss ideas

**Comment by sadiqevani** [comment]
#97

**Comment by maptuhec** [comment]
https://hackmd.aepps.com/EbBmEMDYA4HYBYC0AGAjAY2Y+Bmc1Fg4tlZUdgATAJgE5RqBWaoA
